// 默认词库 - 七年级期中版（吾日三省吾身优先）
const WORD_BANK = [
  { "word": "吾日三省吾身", "correct": true },
  { "word": "吾日三醒吾身", "correct": false, "right": "吾日三省吾身" },
  { "word": "朗润", "correct": true },
  { "word": "郎润", "correct": false, "right": "朗润" },
  { "word": "酝酿", "correct": true },
  { "word": "蕴酿", "correct": false, "right": "酝酿" },
  { "word": "嘹亮", "correct": true },
  { "word": "分歧", "correct": true },
  { "word": "分岐", "correct": false, "right": "分歧" },
  { "word": "澄清", "correct": true },
  { "word": "澄青", "correct": false, "right": "澄清" },
  { "word": "粗犷", "correct": true },
  { "word": "粗旷", "correct": false, "right": "粗犷" },
  { "word": "贮蓄", "correct": true },
  { "word": "确凿", "correct": true },
  { "word": "攲斜", "correct": true },
  { "word": "宽恕", "correct": true },
  { "word": "宽怒", "correct": false, "right": "宽恕" },
  { "word": "收敛", "correct": true },
  { "word": "倏忽", "correct": true },
  { "word": "倏乎", "correct": false, "right": "倏忽" },
  { "word": "伶仃", "correct": true },
  { "word": "伶丁", "correct": false, "right": "伶仃" },
  { "word": "嶙峋", "correct": true },
  { "word": "迂回", "correct": true },
  { "word": "卓越", "correct": true },
  { "word": "卓跃", "correct": false, "right": "卓越" },
  { "word": "笃志", "correct": true },
  { "word": "笃智", "correct": false, "right": "笃志" },
  { "word": "痴想", "correct": true },
  { "word": "诱惑", "correct": true },
  { "word": "诱或", "correct": false, "right": "诱惑" },
  { "word": "点缀", "correct": true },
  { "word": "点辍", "correct": false, "right": "点缀" },
  { "word": "绽放", "correct": true },
  { "word": "淀放", "correct": false, "right": "绽放" },
  { "word": "倾向", "correct": true },
  { "word": "倾项", "correct": false, "right": "倾向" },
  { "word": "谋生", "correct": true },
  { "word": "谋声", "correct": false, "right": "谋生" },
  { "word": "铭记", "correct": true },
  { "word": "明记", "correct": false, "right": "铭记" },
  { "word": "叛逆", "correct": true },
  { "word": "丑陋", "correct": true },
  { "word": "憧憬", "correct": true },
  { "word": "憧景", "correct": false, "right": "憧憬" },
  { "word": "瘫痪", "correct": true },
  { "word": "摊痪", "correct": false, "right": "瘫痪" },
  { "word": "沐浴", "correct": true },
  { "word": "沫浴", "correct": false, "right": "沐浴" },
  { "word": "慈怜", "correct": true },
  { "word": "慈连", "correct": false, "right": "慈怜" },
  { "word": "褪色", "correct": true },
  { "word": "退色", "correct": false, "right": "褪色" },
  { "word": "焚香", "correct": true },
  { "word": "截然", "correct": true },
  { "word": "结然", "correct": false, "right": "截然" },
  { "word": "怦怦", "correct": true },
  { "word": "砰砰", "correct": false, "right": "怦怦" },
  { "word": "尴尬", "correct": true },
  { "word": "尬尴", "correct": false, "right": "尴尬" },
  { "word": "荣耀", "correct": true },
  { "word": "荣曜", "correct": false, "right": "荣耀" },
  { "word": "绰号", "correct": true },
  { "word": "抖擞", "correct": true },
  { "word": "抖数", "correct": false, "right": "抖擞" },
  { "word": "捉迷藏", "correct": true },
  { "word": "捉谜藏", "correct": false, "right": "捉迷藏" },
  { "word": "澄净", "correct": true },
  { "word": "澄静", "correct": false, "right": "澄净" },
  { "word": "撩起", "correct": true },
  { "word": "瞭起", "correct": false, "right": "撩起" },
  { "word": "偌大", "correct": true },
  { "word": "若大", "correct": false, "right": "偌大" },
  { "word": "屋檐", "correct": true },
  { "word": "屋沿", "correct": false, "right": "屋檐" },
  { "word": "瞬间", "correct": true },
  { "word": "寥廓", "correct": true },
  { "word": "辽廓", "correct": false, "right": "寥廓" },
  { "word": "芦篷", "correct": true },
  { "word": "芦蓬", "correct": false, "right": "芦篷" },
  { "word": "梦寐", "correct": true },
  { "word": "梦昧", "correct": false, "right": "梦寐" },
  { "word": "凝成", "correct": true },
  { "word": "凝城", "correct": false, "right": "凝成" },
  { "word": "桌越", "correct": false, "right": "卓越" },
  { "word": "预兆", "correct": true },
  { "word": "预召", "correct": false, "right": "预兆" },
  { "word": "督志", "correct": false, "right": "笃志" },
  { "word": "哀号", "correct": true },
  { "word": "哀嚎", "correct": false, "right": "哀号" },
  { "word": "气氛", "correct": true },
  { "word": "逃窜", "correct": true },
  { "word": "干扰", "correct": true },
  { "word": "干挠", "correct": false, "right": "干扰" },
  { "word": "椭圆", "correct": true },
  { "word": "妥圆", "correct": false, "right": "椭圆" },
  { "word": "愚蠢", "correct": true },
  { "word": "鱼蠢", "correct": false, "right": "愚蠢" },
  { "word": "炫耀", "correct": true },
  { "word": "炫曜", "correct": false, "right": "炫耀" },
  { "word": "踪迹", "correct": true },
  { "word": "宗迹", "correct": false, "right": "踪迹" },
  { "word": "嬉戏", "correct": true },
  { "word": "嘻戏", "correct": false, "right": "嬉戏" },
  { "word": "泥泞", "correct": true },
  { "word": "泥泥", "correct": false, "right": "泥泞" },
  { "word": "闷热", "correct": true },
  { "word": "疲倦不堪", "correct": true },
  { "word": "疲卷不堪", "correct": false, "right": "疲倦不堪" },
  { "word": "花团锦簇", "correct": true },
  { "word": "花团锦族", "correct": false, "right": "花团锦簇" },
  { "word": "踉踉跄跄", "correct": true },
  { "word": "踉踉呛呛", "correct": false, "right": "踉踉跄跄" },
  { "word": "拆散", "correct": true },
  { "word": "折散", "correct": false, "right": "拆散" },
  { "word": "仿膳", "correct": true },
  { "word": "仿善", "correct": false, "right": "仿膳" },
  { "word": "嗅到", "correct": true },
  { "word": "臭到", "correct": false, "right": "嗅到" },
  { "word": "逮住", "correct": true },
  { "word": "并蒂", "correct": true },
  { "word": "并帝", "correct": false, "right": "并蒂" },
  { "word": "宽数", "correct": false, "right": "宽恕" },
  { "word": "磕头", "correct": true },
  { "word": "嗑头", "correct": false, "right": "磕头" },
  { "word": "搓捻", "correct": true },
  { "word": "搓拈", "correct": false, "right": "搓捻" },
  { "word": "惨境", "correct": true },
  { "word": "顷向", "correct": false, "right": "倾向" },
  { "word": "呆板", "correct": true },
  { "word": "铭计", "correct": false, "right": "铭记" },
  { "word": "判逆", "correct": false, "right": "叛逆" },
  { "word": "镶边", "correct": true },
  { "word": "锥形", "correct": true },
  { "word": "晕倒", "correct": true },
  { "word": "陡峭", "correct": true },
  { "word": "疲乏", "correct": true },
  { "word": "疲泛", "correct": false, "right": "疲乏" },
  { "word": "撩亮", "correct": false, "right": "嘹亮" },
  { "word": "喧腾", "correct": true },
  { "word": "喧滕", "correct": false, "right": "喧腾" },
  { "word": "引颈", "correct": true },
  { "word": "窸窣", "correct": true },
  { "word": "随风直到夜郎西", "correct": false, "right": "随君直到夜郎西" },
  { "word": "随君直到夜郎西", "correct": true },
  { "word": "随君直到夜朗西", "correct": false, "right": "随君直到夜郎西" },
  { "word": "人不知而不愠", "correct": true },
  { "word": "人不知而不温", "correct": false, "right": "人不知而不愠" },
  { "word": "海日生残夜", "correct": true },
  { "word": "海日升残夜", "correct": false, "right": "海日生残夜" },
  { "word": "海日生残月", "correct": false, "right": "海日生残夜" },
  { "word": "江春入旧年", "correct": true },
  { "word": "江村入旧年", "correct": false, "right": "江春入旧年" },
  { "word": "学而不思则罔", "correct": true },
  { "word": "学而不思则网", "correct": false, "right": "学而不思则罔" },
  { "word": "分歧（qí）", "correct": true },
  { "word": "分岐（qǐ）", "correct": false, "right": "分歧（qí）" },
  { "word": "嫩芽（nèn）", "correct": true },
  { "word": "嫰芽（nèn）", "correct": false, "right": "嫩芽（nèn）" },
  { "word": "整宿（xiǔ）", "correct": true },
  { "word": "整宿（sù）", "correct": false, "right": "整宿（xiǔ）" },
  { "word": "侍弄（shì）", "correct": true },
  { "word": "侍弄（sì）", "correct": false, "right": "侍弄（shì）" },
  { "word": "絮叨（xù）", "correct": true },
  { "word": "絮叨（xū）", "correct": false, "right": "絮叨（xù）" },
  { "word": "淡雅（yǎ）", "correct": true },
  { "word": "淡雅（yā）", "correct": false, "right": "淡雅（yǎ）" },
  { "word": "憔悴（qiáo）", "correct": true },
  { "word": "憔悴（jiāo）", "correct": false, "right": "憔悴（qiáo）" },
  { "word": "脸颊（jiá）", "correct": true },
  { "word": "脸颊（xiá）", "correct": false, "right": "脸颊（jiá）" },
  { "word": "不禁（jīn）", "correct": true },
  { "word": "不禁（jìn）", "correct": false, "right": "不禁（jīn）" },
  { "word": "咽喉（yān）", "correct": true },
  { "word": "咽喉（yàn）", "correct": false, "right": "咽喉（yān）" },
  { "word": "涟漪（yī）", "correct": true },
  { "word": "涟漪（yì）", "correct": false, "right": "涟漪（yī）" },
  { "word": "占卜（bǔ）", "correct": true },
  { "word": "占卜（pǔ）", "correct": false, "right": "占卜（bǔ）" },
  { "word": "譬如（pì）", "correct": true },
  { "word": "譬如（bì）", "correct": false, "right": "譬如（pì）" },
  { "word": "暂时（zàn）", "correct": true },
  { "word": "暂时（zhàn）", "correct": false, "right": "暂时（zàn）" },
  { "word": "遗憾（hàn）", "correct": true },
  { "word": "遗憾（hán）", "correct": false, "right": "遗憾（hàn）" },
  { "word": "潜力（qián）", "correct": true },
  { "word": "潜力（jiān）", "correct": false, "right": "潜力（qián）" },
  { "word": "威慑（shè）", "correct": true },
  { "word": "威慑（shé）", "correct": false, "right": "威慑（shè）" },
  { "word": "停滞（zhì）", "correct": true },
  { "word": "停滞（zhǐ）", "correct": false, "right": "停滞（zhì）" },
  { "word": "须臾（yú）", "correct": true },
  { "word": "须臾（yǔ）", "correct": false, "right": "须臾（yú）" },
  { "word": "嘈杂（cáo）", "correct": true },
  { "word": "嘈杂（zào）", "correct": false, "right": "嘈杂（cáo）" },
  { "word": "应和（hè）", "correct": true },
  { "word": "应和（hé）", "correct": false, "right": "应和（hè）" },
  { "word": "黄晕（yùn）", "correct": true },
  { "word": "黄晕（yūn）", "correct": false, "right": "黄晕（yùn）" },
  { "word": "朗润（rùn）", "correct": true },
  { "word": "朗润（lùn）", "correct": false, "right": "朗润（rùn）" },
  { "word": "酝酿（niàng）", "correct": true },
  { "word": "酝酿（liàng）", "correct": false, "right": "酝酿（niàng）" },
  { "word": "发酵（jiào）", "correct": true },
  { "word": "发酵（xiào）", "correct": false, "right": "发酵（jiào）" },
  { "word": "贮蓄（zhù）", "correct": true },
  { "word": "贮蓄（chǔ）", "correct": false, "right": "贮蓄（zhù）" },
  { "word": "看护（kān）", "correct": true },
  { "word": "看护（kàn）", "correct": false, "right": "看护（kān）" },
  { "word": "弧形（hú）", "correct": true },
  { "word": "弧形（hū）", "correct": false, "right": "弧形（hú）" },
  { "word": "刹那（chà）", "correct": true },
  { "word": "刹那（shā）", "correct": false, "right": "刹那（chà）" },
  { "word": "蜷曲（quán）", "correct": true },
  { "word": "蜷曲（juǎn）", "correct": false, "right": "蜷曲（quán）" },
  { "word": "栖息（qī）", "correct": true },
  { "word": "栖息（xī）", "correct": false, "right": "栖息（qī）" },
  { "word": "枯涸（hé）", "correct": true },
  { "word": "枯涸（gù）", "correct": false, "right": "枯涸（hé）" },
  { "word": "归泊（bó）", "correct": true },
  { "word": "归泊（pō）", "correct": false, "right": "归泊（bó）" },
  { "word": "迸溅（bèng）", "correct": true },
  { "word": "迸溅（bìng）", "correct": false, "right": "迸溅（bèng）" },
  { "word": "伫立（zhù）", "correct": true },
  { "word": "伫立（chù）", "correct": false, "right": "伫立（zhù）" },
  { "word": "挑逗（tiǎo）", "correct": true },
  { "word": "挑逗（tiāo）", "correct": false, "right": "挑逗（tiǎo）" },
  { "word": "绽放（zhàn）", "correct": true },
  { "word": "绽放（dìng）", "correct": false, "right": "绽放（zhàn）" },
  { "word": "耸立（sǒng）", "correct": true },
  { "word": "耸立（shǒng）", "correct": false, "right": "耸立（sǒng）" },
  { "word": "纳罕（nà）", "correct": true },
  { "word": "纳罕（là）", "correct": false, "right": "纳罕（nà）" },
  { "word": "峭壁（qiào）", "correct": true },
  { "word": "峭壁（xiào）", "correct": false, "right": "峭壁（qiào）" },
  { "word": "颤抖（chàn）", "correct": true },
  { "word": "颤抖（zhàn）", "correct": false, "right": "颤抖（chàn）" },
  { "word": "屡次（lǚ）", "correct": true },
  { "word": "屡次（lǜ）", "correct": false, "right": "屡次（lǚ）" },
  { "word": "痴想（chī）", "correct": true },
  { "word": "痴想（zhī）", "correct": false, "right": "痴想（chī）" },
  { "word": "诱惑（yòu）", "correct": true },
  { "word": "诱惑（xiù）", "correct": false, "right": "诱惑（yòu）" },
  { "word": "躯壳（qiào）", "correct": true },
  { "word": "躯壳（ké）", "correct": false, "right": "躯壳（qiào）" },
  { "word": "匀称（chèn）", "correct": true },
  { "word": "匀称（chēng）", "correct": false, "right": "匀称（chèn）" },
  { "word": "弥漫（mí）", "correct": true },
  { "word": "弥漫（ní）", "correct": false, "right": "弥漫（mí）" },
  { "word": "吮吸（shǔn）", "correct": true },
  { "word": "吮吸（yǔn）", "correct": false, "right": "吮吸（shǎn）" },
  { "word": "盔甲（kuī）", "correct": true },
  { "word": "盔甲（kūn）", "correct": false, "right": "盔甲（kuī）" },
  { "word": "妒忌（dù）", "correct": true },
  { "word": "妒忌（tù）", "correct": false, "right": "妒忌（dù）" },
  { "word": "大厦（shà）", "correct": true },
  { "word": "大厦（xià）", "correct": false, "right": "大厦（shà）" },
  { "word": "轨道（guǐ）", "correct": true },
  { "word": "轨道（guì）", "correct": false, "right": "轨道（guǐ）" },
  { "word": "愕然（è）", "correct": true },
  { "word": "愕然（wù）", "correct": false, "right": "愕然（è）" },
  { "word": "滑稽（jī）", "correct": true },
  { "word": "滑稽（jì）", "correct": false, "right": "滑稽（jī）" },
  { "word": "勋章（xūn）", "correct": true },
  { "word": "勋章（xùn）", "correct": false, "right": "勋章（xūn）" },
  { "word": "赏赐（cì）", "correct": true },
  { "word": "赏赐（sì）", "correct": false, "right": "赏赐（cì）" },
  { "word": "称职（chèn）", "correct": true },
  { "word": "称职（chēng）", "correct": false, "right": "称职（chèn）" },
  { "word": "绵延（mián）", "correct": true },
  { "word": "绵延（miǎn）", "correct": false, "right": "绵延（mián）" },
  { "word": "孪生（luán）", "correct": true },
  { "word": "孪生（luàn）", "correct": false, "right": "孪生（luán）" },
  { "word": "小心翼翼（yì）", "correct": true },
  { "word": "小心翼翼（yí）", "correct": false, "right": "小心翼翼（yì）" },
  { "word": "忍俊不禁（jīn）", "correct": true },
  { "word": "忍俊不禁（jìn）", "correct": false, "right": "忍俊不禁（jīn）" },
  { "word": "灰心丧气（sàng）", "correct": true },
  { "word": "灰心丧气（sāng）", "correct": false, "right": "灰心丧气（sàng）" },
  { "word": "一丝不苟（gǒu）", "correct": true },
  { "word": "一丝不苟（gōu）", "correct": false, "right": "一丝不苟（gǒu）" },
  { "word": "随声附和（hè）", "correct": true },
  { "word": "随声附和（hé）", "correct": false, "right": "随声附和（hè）" },
  { "word": "骇人听闻（hài）", "correct": true },
  { "word": "骇人听闻（hǎi）", "correct": false, "right": "骇人听闻（hài）" }
];

function sampleWord(probWrong = 0.10, forceWrong = false) {
  const wrongs = WORD_BANK.filter(w => !w.correct);
  const rights = WORD_BANK.filter(w => w.correct);
  // 如果强制错误，直接返回错误词
  if (forceWrong && wrongs.length > 0) {
    const w = wrongs[Math.floor(Math.random()*wrongs.length)]; 
    return { text:w.word, correct:false, right:w.right }; 
  }
  // 否则按概率随机
  const useWrong = Math.random() < probWrong && wrongs.length > 0;
  if (useWrong) { 
    const w = wrongs[Math.floor(Math.random()*wrongs.length)]; 
    return { text:w.word, correct:false, right:w.right }; 
  }
  const r = rights[Math.floor(Math.random()*rights.length)]; 
  return { text:r.word, correct:true };
}
